# Site settings
title: Centre de Ressources sur les Idées et les Pratiques d'Extrême Droite & Associées
header-img: img/home-bg.jpg
email: pierre.bezoukhov@riseup.net
copyright_name: CRIPEDA
description: Le Centre de Ressources sur les Idées et les Pratiques d'Extrême-Droite & Associées (CRIPEDA) a été créé fin 2014 pour comprendre et s'opposer à l'extrême-droite. Il regroupe des citoyen(e)s préoccupé(e)s par la résurgence en France de l'extrême-droite et de ses idées, y compris au sein de partis généralement considérés comme démocratiques.
baseurl: ""
url: http://www.cripeda.org
twitter_username: cripeda
github_username:  cripeda
facebook_username:  cripeda.france
email_username:  pierre.bezoukhov@riseup.net

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
